version: '3.9'
services:
  web:
    build: .
    command: ./wait-for-it.sh mysql:5432 -- ./docker-entrypoint.sh
    ports:
      - 8000:8000
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 1337:443
    volumes:
      - ./media:/app/media
      - ./static:/app/static
      - /root/cert/:/etc/nginx/cert
    depends_on:
      - web


volumes:
  postgresdata:
  